apiVersion: v2
appVersion: "1.12.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
description: Your self-hosted bookmark archive. Free and open source - stu version
home: https://truecharts.org/charts/incubator/linkace
icon: https://truecharts.org/img/hotlink-ok/chart-icons/linkace.png
keywords:
  - linkace
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: linkace
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/linkace
  - https://www.linkace.org/docs/
  - https://github.com/linkace/linkace
version: 8.0.0
annotations:
  truecharts.org/category: media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
